# Generated by Django 5.2.10 on 2026-02-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanBong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=200)),
                ('vi_do', models.FloatField()),
                ('kinh_do', models.FloatField()),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
