# Generated by Django 5.2.10 on 2026-02-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên người đặt')),
                ('sdt', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('ngay_dat', models.DateField(verbose_name='Ngày đá')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('thoi_luong', models.IntegerField(default=60, verbose_name='Thời lượng (phút)')),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ Duyệt'), ('DA_DUYET', 'Đã Duyệt'), ('TU_CHOI', 'Từ Chối')], default='CHO_DUYET', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanbong', verbose_name='Sân')),
            ],
        ),
    ]
