# Generated by Django 5.2.10 on 2026-02-02 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0002_datsan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sp', models.CharField(max_length=100, verbose_name='Tên sản phẩm')),
                ('loai', models.CharField(choices=[('THUE', 'Thuê (Giày/Vợt/Áo)'), ('DO_AN', 'Đồ Ăn / Nước Uống')], default='DO_AN', max_length=20)),
                ('gia', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá tiền')),
            ],
        ),
        migrations.AddField(
            model_name='datsan',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='tien_coc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền cọc (30%)'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền dự kiến'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='gio_bat_dau',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='ho_ten',
            field=models.CharField(max_length=100, verbose_name='Họ tên (người đá)'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='ngay_dat',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='san',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanbong'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ Duyệt'), ('DA_DUYET', 'Đã Duyệt (Đã Cọc)'), ('TU_CHOI', 'Hủy Bỏ')], default='CHO_DUYET', max_length=20),
        ),
        migrations.AddField(
            model_name='datsan',
            name='dich_vu_kem',
            field=models.ManyToManyField(blank=True, to='quanlysan.sanpham', verbose_name='Dịch vụ dùng thêm'),
        ),
    ]
