# Generated by Django 5.2.10 on 2026-02-02 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0003_sanpham_datsan_khach_hang_datsan_tien_coc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanbong',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='san_bong/', verbose_name='Hình ảnh sân'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='san_pham/', verbose_name='Hình ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='gio_bat_dau',
            field=models.TimeField(verbose_name='Giờ bắt đầu'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='ngay_dat',
            field=models.DateField(verbose_name='Ngày đặt'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='san',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysan.sanbong', verbose_name='Sân bóng'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ Duyệt'), ('DA_DUYET', 'Đã Duyệt (Đã Cọc)'), ('TU_CHOI', 'Hủy Bỏ')], default='CHO_DUYET', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='dia_chi',
            field=models.CharField(max_length=200, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='gia_tien',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá thuê (VNĐ/h)'),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='kinh_do',
            field=models.FloatField(verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='ten_san',
            field=models.CharField(max_length=100, verbose_name='Tên sân'),
        ),
        migrations.AlterField(
            model_name='sanbong',
            name='vi_do',
            field=models.FloatField(verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='loai',
            field=models.CharField(choices=[('THUE', 'Thuê (Giày/Vợt/Áo)'), ('DO_AN', 'Đồ Ăn / Nước Uống')], default='DO_AN', max_length=20, verbose_name='Loại'),
        ),
    ]
