# Generated by Django 5.2.10 on 2026-02-02 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysan', '0004_sanbong_hinh_anh_sanpham_hinh_anh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sanbong',
            name='danh_gia',
            field=models.FloatField(default=5.0, verbose_name='Điểm đánh giá (Sao)'),
        ),
        migrations.AddField(
            model_name='sanbong',
            name='khoang_cach',
            field=models.FloatField(default=1.5, verbose_name='Khoảng cách (km)'),
        ),
        migrations.AddField(
            model_name='sanbong',
            name='nguoi_yeu_thich',
            field=models.ManyToManyField(blank=True, related_name='san_yeu_thich', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanbong',
            name='so_luot_danh_gia',
            field=models.IntegerField(default=0, verbose_name='Số lượt review'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='dich_vu_kem',
            field=models.ManyToManyField(blank=True, to='quanlysan.sanpham', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='ho_ten',
            field=models.CharField(max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='sdt',
            field=models.CharField(max_length=15, verbose_name='SĐT'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='tien_coc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ Duyệt'), ('DA_DUYET', 'Đã Duyệt (Đã Cọc)'), ('TU_CHOI', 'Hủy Bỏ')], default='CHO_DUYET', max_length=20),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='san_pham/', verbose_name='Hình ảnh'),
        ),
    ]
